# Generated by Django 2.0 on 2018-07-30 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0002_auto_20180730_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingChart',
            new_name='ShoppingCart',
        ),
    ]
